-- DROP TABLE AUTHORITIES;
-- DROP TABLE USERS;

-- SANMARU.USERS definition

CREATE TABLE "SANMARU"."USERS"
(	"USERNAME" NVARCHAR2(128),
     "PASSWORD" NVARCHAR2(128) NOT NULL ENABLE,
     "MFA" CHAR(1) DEFAULT '0',
     "SECRET" NVARCHAR2(128),
     "ENABLED" CHAR(1) NOT NULL ENABLE,
     PRIMARY KEY ("USERNAME")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "SYSTEM"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

-- SANMARU.AUTHORITIES definition

CREATE TABLE "SANMARU"."AUTHORITIES"
(	"USERNAME" NVARCHAR2(128) NOT NULL ENABLE,
     "AUTHORITY" NVARCHAR2(128) NOT NULL ENABLE,
     CONSTRAINT "AUTHORITIES_UNIQUE" UNIQUE ("USERNAME", "AUTHORITY")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "SYSTEM"  ENABLE,
     CONSTRAINT "AUTHORITIES_FK1" FOREIGN KEY ("USERNAME")
         REFERENCES "SANMARU"."USERS" ("USERNAME") ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
